### ISSUE TITLE
Missing [real part of cylinder ior] in non-elliptical cross-section example

### ISSUE THREAD

**Issue by RiverIntheSky** [mandyxmq/WaveOpticsFiber#1]
`genDist.cpp` reads the 8th argument as the real part of the IOR, and the 9th argument as the imaginary part of the IOR, but example in `README.md` does not provide the real part of the ior:
```
360 100 50 [?] ../ior/silkK_double.binary
```
causing error:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
fish: Job 2, “./Sim silk 0 ../crosssection/xv…” terminated by signal SIGABRT (Abort)
```

**Comment by mandyxmq** [comment]
Thanks for pointing this out. README is updated.
